import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Providers from './components/Providers'
import Link from "next/link";
import Navigation from './components/Nav/Navigation';

const poppins = Roboto({
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" className='min-h-screen'>
      <body className={poppins.className}>       
          <Providers> {/* SessionProvider */}
            <Navigation/>
            <div className='max-w-[1280px] w-full flex flex-row m-auto font-sans'>
              {children}
            </div>
          </Providers>
      </body>
    </html>
  )
}
