import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './components/Providers'
import Link from "next/link";
import Navigation from './components/Navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        <Providers> {/* SessionProvider */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
