import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Providers from './components/Providers'
import Link from "next/link";
import Navigation from './components/Nav/Navigation';

const poppins = Roboto({
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" className='min-h-screen w-full bg-slate-100'>
      <body className={poppins.className}>       
          <Providers> {/* SessionProvider */}
            <div className='core max-w-screen-2xl w-full min-h-screen flex flex-row items-start font-sans m-auto '>
              <div className='flex flex-col w-full justify-center items-center  '>
                <Navigation/>
                {children}
              </div>
            </div>
          </Providers>
      </body>
    </html>
  )
}
